services:
  minecraft:
    image: tpotcraft:latest
    container_name: tpotcraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
    environment:
      - JAVA_OPTS=-Xmx4G -Xms2G -XX:+UseG1GC
    tty: true
    stdin_open: true